### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by TanguyOrtegat** [CreepPork/DikeCAD#1]
thanks for releasing the reessource, but i did try it, but never got it working. Maybe possible to have a tutorial or some explanations ? thanks!

What i did:
- npm install
- composer install
- navigate trough index/php

I do see a screen but error 500. 

Thanks for your patience

**Comment by CreepPork** [comment]
### Development
1. Clone or fork the repo
2. `composer install`
3. `npm install`
4. `npm run dev`
5. `cp .env.example .env`
6. `php artisan key:generate`
7. Configure the `.env` file
8. `php artisan storage:link`
9. `php artisan migrate`
11. `php artisan serve` (_if not running on a PHP server_)
16. Get working!

### Production
1. Clone or download the repo
2. `composer install`
3. `npm install`
4. `npm run prod`
5. `cp .env.example .env`
6. `php artisan key:generate`
7. Configure `.env` file
8. `php artisan storage:link`
13. `php artisan migrate --force`
15. `composer install --optimize-autoloader --no-dev`
16. `php artisan config:cache`
17. `php artisan route:cache`
19. Done!

**Comment by CreepPork** [comment]
https://laravel.com/docs/5.8/installation
